# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel
a = User.create(username: 'Parag', email: 'parag@gmail.com')
b = User.create(username: 'Jon', email: 'jon@gmail.com')
c = User.create(username: 'Daniel', email: 'daniel@gmail.com')
d = User.create(username: 'Peng', email: 'peng@gmail.com')
e = User.create(username: 'Dev', email: 'dev@gmail.com')
f = User.create(username: 'Stephan', email: 'stephan@gmail.com')
g = User.create(username: 'Jeff', email: 'jeff@gmail.com')
h = User.create(username: 'George', email: 'george@gmail.com')

t1 = Team.create(name: 'Chicago Bears')
t2 = Team.create(name: 'Detroit Lions')
t3 = Team.create(name: 'Green Bay Packers')
t4 = Team.create(name: 'Minnesota Vikings')
t5 = Team.create(name: 'San Francisco 49ers')
t6 = Team.create(name: 'Arizona Cardinals')
t7 = Team.create(name: 'Seattle Seahawks')
t8 = Team.create(name: 'St. Louis Rams')
t9 = Team.create(name: 'Houston Texans')
t10 = Team.create(name: 'Tennessee Titans')
t11 = Team.create(name: 'New Orleans Saints')
t12 = Team.create(name: 'Atlanta Falcons')
t13 = Team.create(name: 'Tampa Bay Buccaneers')
t14 = Team.create(name: 'Dallas Cowboys')
t15 = Team.create(name: 'New York Giants')
t16 = Team.create(name: 'Philadelphia Eagles')
t17 = Team.create(name: 'Washington Redskins')
t18 = Team.create(name: 'Jacksonville Jaguars')
t19 = Team.create(name: 'Carolina Panthers')
t20 = Team.create(name: 'Indianapolis Colts')
t21 = Team.create(name: 'Cincinnati Bengals')
t22 = Team.create(name: 'Baltimore Ravens')
t23 = Team.create(name: 'Cleveland Browns')
t24 = Team.create(name: 'Pittsburgh Steelers')
t25 = Team.create(name: 'Denver Broncos')
t26 = Team.create(name: 'Kansas City Chiefs')
t27 = Team.create(name: 'Oakland Raiders')
t28 = Team.create(name: 'San Diego Chargers')
t29 = Team.create(name: 'Buffalo Bills')
t30 = Team.create(name: 'Miami Dolphins')
t31 = Team.create(name: 'New England Patriots')
t32 = Team.create(name: 'New York Jets')